/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class net_bc100dev_rpisetup_lib_Mount */

#ifndef _Included_net_bc100dev_rpisetup_lib_Mount
#define _Included_net_bc100dev_rpisetup_lib_Mount
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bc100dev_rpisetup_lib_Mount
 * Method:    nMount
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bc100dev_rpisetup_lib_Mount_nMount
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     net_bc100dev_rpisetup_lib_Mount
 * Method:    nUnmount
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bc100dev_rpisetup_lib_Mount_nUnmount
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
